#import "/metadata.typ": *
#pagebreak()
= Supervision Interface (Frontend)
<sec:interface-supervision>

//#lorem(30)

#option-style(type:option.type)[
Contenu attendu
- *Choix UI/UX :* Bref aperçu des choix d'interface avec React.
- *Flux de données :* Explication de la manière dont les données des microservices sont récupérées et affichées en temps réel.

Illustrations à prévoir
#block(fill: luma(245), inset: 12pt, radius: 4pt, width: 100%)[
  - 2 ou 3 captures d'écran de l'interface (Dashboard général, vue de gestion des badges ou des limites de courant).
]
]

== Project Organization and React Architecture

The frontend project is developed using React and TypeScript, which ensures strong static typing for the entire codebase and guarantees greater robustness. The file structure has been designed to clearly separate responsibilities, following a modular architecture.

Within the main src directory, the code is organized into several key folders:

* api *: centralizes all communication functions with the backend and the database (authentication, charging stations, sessions, etc.).\
* components *: groups the reusable visual elements of the interface, with a layout subfolder dedicated to the overall structure of the application.\
* context *: contains the global state providers, used for authentication management and theme application.\
* pages *: segments the different views of the application, with a clear separation between the authentication screens and the dashboards (divided between administrator and user).

Files located at the project root, such as types.ts or theme.css, complete this structure to define the global TypeScript interfaces and the application's graphic charter, respectively.

== Network Communication and State Management

All network communications in this project rely on the native JavaScript fetch API. To standardize data exchanges with the database, a custom utility function (fetchHasura) was developed. It is responsible for encapsulating GraphQL requests as standard HTTP POST requests to the Hasura engine, while properly handling returned errors to transmit them to the user interface. This same native approach is used to communicate with the Go-developed microservices.

In the context of this Proof of Concept (PoC), data retrieval occurs upon the initial loading of the components. Data updating is done transactionally or via a manual refresh by the user, which significantly reduces the load on the central server.

State management fully leverages native React tools. The application's global state, including connection status and profile information, is centralized using the Context API. Local states, such as form data or lists, are managed in isolation within each component via the useState hook.

Regarding security, the password is hashed in SHA-256 on the client side before being transmitted during account creation. Subsequently, the JWT token generated by the authentication service is stored in the browser (localStorage). The request function automatically intercepts this token to inject it into the HTTP header of every outgoing request. A global validation logic allows for a forced logout to be triggered if the token is expired or deemed invalid.

== Design and Usability (UI/UX)

The visual aspect of the platform was entirely custom-designed. The interface relies exclusively on pure CSS combined with inline styles typed via React.CSSProperties, which prevents syntax errors while maintaining a dynamic approach.

The application is structured around a global style file defining a set of CSS variables. This approach enables centralized management of the graphic charter and facilitated the native implementation of a light mode and a dark mode. Navigation revolves around a main layout component that encompasses a top navigation bar (Topbar) and a side menu (Sidebar).

#figure(
  image("../resources/img/stations.png", width: 100%),
  caption: [Overview of the Layout (Topbar + Sidebar) and preview of the dark theme.],
) <fig:stations>

To ensure instant readability of the fleet's status, a strict semantic color coding was implemented via these global CSS variables:

* Green (Emerald Green) *: Charging station charging or active.\
* Blue *: Charging station available and ready for use.\
* Red *: Charging station offline, in error, or illegal session.\

Finally, for the visual representation of complex data (telemetry, power curves, consumption statistics), the open-source library Recharts was integrated. Its components allow for the generation of dynamic, interactive, and fluid charts, integrating perfectly into the React ecosystem.

#pagebreak()
== Main Views Development

The interface was segmented to meet the specific needs of two types of profiles: standard users and administrators.

=== User Interface
The view intended for end users was designed to be direct and informative, revolving around three main tabs:

* Overview (Dashboard) *: This central screen highlights the parking availability. It displays the user's active charging session in real time, or alternatively, the details of their last session. Global metrics complete this view.\
* My Sessions *: A summary table offering the complete history of charging sessions, with filtering capabilities.\
* My Badges *: A management interface allowing the addition, modification, or revocation of RFID or NFC badges associated with the user's profile.

#figure(
  image("../resources/img/user_dashboard.png", width: 100%),
  caption: [User version of the Dashboard, featuring the overview view and the My Sessions and My Badges tabs.],
) <fig:user_dashboard>

#pagebreak()
=== Administrator Interface
Accounts with elevated rights have access to a set of advanced supervision and configuration tools, distributed across several views:

* Global Supervision *: The fleet's control center. It consolidates the status of all chargers, the instantaneous power drawn by the system, and the total energy distributed. A graph based on a 24-hour sliding time window traces the precise evolution of the overall load, complemented by an exhaustive list of active sessions.\
* Charging Stations *: The hardware configuration interface. It allows for listing the stations, defining their priority levels, and accessing the management of power blocks to configure the electrical limits of the power supply groups.\
* Badge Management *: An extended view allowing the supervision of all system badges (recognized and unknown) and the auditing of sessions linked to a specific identifier.\
* Users *: The account administration panel, allowing for the modulation of permissions and the inspection of transaction volumes per collaborator.

#figure(
  image("../resources/img/admin_dashboard.png", width: 100%),
  caption: [Administrator version of the Dashboard, featuring the global supervision view and the Charging Stations, Badge Management, and Users tabs.],
) <fig:admin_dashboard>

#pagebreak()
=== Detailed Views and Profile
Regardless of the authorization level, clicking on a transaction (from any view) opens a detailed analysis screen of the charging session. This screen renders the temporal curve of the power drawn via an interactive chart and consolidates key indicators. For administrators, this view is enriched with a technical activity log listing the station's events, a diagnostic capability made possible by the richness of the OCPP protocol frames.

#figure(
  image("../resources/img/session_detail.png", width: 100%),
  caption: [Detailed view of a charging session (with the power variation curve).],
) <fig:session_detail>

Finally, a profile configuration section is available for each account, ensuring user autonomy in managing their personal data and login credentials.